name: Cypress Test
on: [push]
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v3.3.0
     - name: Cypress.io
       uses: cypress-io/github-action@v5.0.8
     
